### ISSUE TITLE
Table integration (conflict with edittable)

### ISSUE THREAD

**Issue by stefanobasta** [micgro42/dokuwiki-plugin-structsection#1]
Table integration in the type section works fine, but with the plugin edittable it creates problems during the view. It could be that the table will be double (one stacked over the other).

**Comment by micgro42** [comment]
I do not know how you even got using the edittable-editor within the struct-sections, but I now removed the editbutton from tables in the section.

Please feel free to reopen, if you do not feel that your issue is resolved :-)
