### ISSUE TITLE
Inline editor is not saving and is not reflected with page editor.

### ISSUE THREAD

**Issue by Anonymous215025** [micgro42/dokuwiki-plugin-structsection#10]
Upon trying to edit something with text already inside, the inline editor does not show existing text that is already present inside the section.

![image](https://user-images.githubusercontent.com/66980022/84719460-aa650d00-af38-11ea-8075-18a97f247e76.png)

The opposite is true. Input I put through the inline section editor does not appear in the page editor struct form.

Sometimes pressing save on either inline editor or page edit will wipe out the entry completely and leave it blank.

![image](https://user-images.githubusercontent.com/66980022/84719661-2a8b7280-af39-11ea-912b-10a8b9943872.png)

I am also using: https://www.dokuwiki.org/plugin:structinputstretch if that matters.

**Comment by micgro42** [comment]
Ah, it seems the struct plugin was changed and so the extra magic that this plugin does no longer matches the internals of struct. That probably happened in cosmocode/dokuwiki-plugin-struct#489.

I think I have a patch that fixes it, there should be a new release available tomorrow that resolves it. 🤞
