### ISSUE TITLE
Missing value in section field prevents all page data from being listed in aggregation

### ISSUE THREAD

**Issue by jv-uzl** [micgro42/dokuwiki-plugin-structsection#5]
For other field types, a missing value just leads to an empty cell in a, say, table aggregation. However, for field type "Section", only page data with a value in the corresponding field will be listed.

**Comment by micgro42** [comment]
I'm sorry, you seem to be mistaken. Pages only show up if they have data in at least one of the displayed schema columns. This is the same for section columns as well as for others.
