### ISSUE TITLE
Struct Section appends markup to entry.

### ISSUE THREAD

**Issue by Anonymous215025** [micgro42/dokuwiki-plugin-structsection#9]
![image](https://user-images.githubusercontent.com/66980022/84719157-d469ff80-af37-11ea-9945-32b5169a6248.png)

I put in some placeholder text and upon pressing save, it appends markup to entry. This happens to both section editor and page edit.

**Comment by micgro42** [comment]
Thank you a lot for reporting this! It should be fixed now and work with the current version of the plugin
